version: "3.9"

services:
  # 1. PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5435}:5432"

  redis:
    image: redis:6-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  # backend:
  #   build:
  #     context: ./backend
  #   env_file:
  #     - ./backend/.env
  #   container_name: express_backend
  #   restart: always
  #   environment:
  #     DB_HOST: db
  #     DB_USER: ${POSTGRES_USER:-user}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     DB_NAME: ${POSTGRES_DB:-mydb}
  #     REDIS_HOST: redis
  #     NODE_PORT: 3001
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - db
  #     - redis
  #
  # frontend:
  #   build:
  #     context: ./frontend
  #   env_file:
  #     - ./frontend/.env
  #   container_name: react_frontend
  #   environment:
  #     REACT_APP_API_URL: http://localhost:3001
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
